security:
    # Password hasher configuration
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # User providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        admin_user_provider:
            entity:
                class: App\Entity\Admin
                property: email

    firewalls:
        # Development tools
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Admin login under /back/admin
        admin:
            pattern: ^/back/admin
            provider: admin_user_provider
            form_login:
                login_path: admin_login
                check_path: admin_login
                enable_csrf: true
                default_target_path: /back/admin/
                username_parameter: _username
                password_parameter: _password
            logout:
                path: admin_logout
                target: /back/admin/login
            entry_point: form_login

        # Main application firewall for regular users
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /
                enable_csrf: true
            logout:
                path: app_logout
                # CORRECTED: This uses the 'target' option, which is available in your version.
                # It specifies the *path* to redirect to after a successful logout.
                # The logic for clearing the cart is handled separately by the LogoutEventSubscriber.
                # Replace '/' with the path to your homepage if it's different.
                target: /
                invalidate_session: true
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /
                always_remember_me: false

    # Access control rules
    access_control:
        - { path: ^/back/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/back/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

    # Role hierarchy (optional but useful)
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # For bcrypt
                time_cost: 3 # For argon2i
                memory_cost: 10 # For argon2i