<?php
namespace App\DataFixtures;

use App\Entity\Gift;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class GiftFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $products = [
            [
                'id' => 1,
                'name' => 'Bracelet personnalisé gravé',
                'price' => 45.00,
                'image' => 'images/store/bracelet-grave-homme_1-879656332.jpg',
                'description' => 'Bracelet en cuir ou acier avec message secret, parfait pour un anniversaire.',
                'category' => 'homme',
                'label' => 'accessoires',
                'stock_quantity' => 100, 
            ],
            [
                'id' => 2,
                'name' => 'Lunettes de soleil style aviator',
                'price' => 120.00,
                'image' => 'images/store/lunnettes.jpg',
                'description' => 'Lunettes polarisées anti-UV avec un design rétro.',
                'category' => 'homme',
                'label' => 'accessoires',
                'stock_quantity' => 50, 
            ],
            [
                'id' => 3,
                'name' => 'Coffret bien-être barbier',
                'price' => 55.00,
                'image' => 'images/store/Coffret-barbe-Grand-scaled-3552640452.jpeg',
                'description' => 'Kit de rasage bio avec huile, baume et brosse en poils de sanglier.',
                'category' => 'homme',
                'label' => 'soins',
                'stock_quantity' => 75,
            ],
            [
                'id' => 4,
                'name' => 'Drone avec caméra 4K',
                'price' => 350.00,
                'image' => 'images/store/drone.webp',
                'description' => 'Drone intuitif, idéal pour les paysages ou événements sportifs.',
                'category' => 'homme',
                'label' => 'technologie',
                'stock_quantity' => 30,
            ],
            [
                'id' => 5,
                'name' => 'Montre connectée GPS',
                'price' => 250.00,
                'image' => 'images/store/montre.jpeg',
                'description' => 'Suivi santé et sommeil avec GPS intégré - modèle Garmin.',
                'category' => 'homme',
                'label' => 'technologie',
                'stock_quantity' => 20,
            ],
            [
                'id' => 6,
                'name' => 'Escape Game Batman',
                'price' => 40.00,
                'image' => 'images/store/BatmanEscape_story_Generique-431929359.png',
                'description' => "Expérience immersive à Paris dans l'univers de Batman.",
                'category' => 'homme',
                'label' => 'loisirs',
                'stock_quantity' => 60,
            ],
            [
                'id' => 7,
                'name' => 'Couteau Laguiole personnalisé',
                'price' => 160.00,
                'image' => 'images/store/Couteau-Laguiole-personnalisé.jpeg',
                'description' => "Ménagère de 24 pièces made in France gravée.",
                'category' => 'homme',
                'label' => 'cuisine',
                'stock_quantity' => 40,
            ],
            [
                'id' => 8,
                'name' => 'Simulateur de vol/voiture',
                'price' => 130.00,
                'image' => 'images/store/simulateur.jpg',
                'description' => "Session de simulation pour passionnés de pilotage.",
                'category' => 'homme',
                'label' => 'loisirs',
                'stock_quantity' => 25,
            ],
            [
                'id' => 9,
                'name' => 'Chemise en lin Bergerac',
                'price' => 119.00,
                'image' => 'images/store/chemise.jpg',
                'description' => "Chemise en tissu respirant, fabrication éthique.",
                'category' => 'homme',
                'label' => 'vêtements',
                'stock_quantity' => 15,
            ],
            [
                'id' => 10,
                'name' => 'Saut en parachute ou parapente',
                'price' => 250.00,
                'image' => 'images/store/parachute.jpg',
                'description' => "Sensations fortes garanties pour un anniversaire mémorable.",
                'category' => 'homme',
                'label' => 'loisirs',
                'stock_quantity' => 10,
            ],
            [
                'id' => 11,
                'name' => 'Coffret DIY cosmétiques bio',
                'price' => 60.00,
                'image' => 'images/store/cosmetic.jpg',
                'description' => "Kit complet pour créer ses propres soins avec livret.",
                'category' => 'femme',
                'label' => 'soins',
                'stock_quantity' => 5,
            ],
            [
                'id' => 12,
                'name' => 'Carte cadeau Sephora',
                'price' => 50.00,
                'image' => 'images/store/carte.jpg',
                'description' => "Choix libre parmi des produits de beauté de luxe.",
                'category' => 'femme',
                'label' => 'soins',
                'stock_quantity' => 0,
            ],
            [
                'id' => 13,
                'name' => 'Housse de couette satin coton',
                'price' => 109.00,
                'image' => 'images/store/satin.jpg',
                'description' => "Housse élégante anti-déshydratation en satin de coton.",
                'category' => 'femme',
                'label' => 'maison',
                'stock_quantity' => 10,
            ],
            [
                'id' => 14,
                'name' => 'Lampe glacière Kooduu',
                'price' => 150.00,
                'image' => 'images/store/lamp.jpg',
                'description' => "Lampe LED Bluetooth avec compartiment glacière.",
                'category' => 'Accessoires',
                'label' => 'maison',
                'stock_quantity' => 20,
            ],
            [
                'id' => 15,
                'name' => 'Bijou infini en argent massif',
                'price' => 29.00,
                'image' => 'images/store/infinity.jpg',
                'description' => "Bague symbole d’éternité en argent, taille ajustable.",
                'category' => 'femme',
                'label' => 'accessoires',
                'stock_quantity' => 30,
            ],
            [
                'id' => 16,
                'name' => 'Robe sur mesure Sumissura',
                'price' => 220.00,
                'image' => 'images/store/robe.jpeg',
                'description' => "Robe personnalisée pour une coupe parfaite.",
                'category' => 'femme',
                'label' => 'vêtements',
                'stock_quantity' => 15,
            ],
            [
                'id' => 17,
                'name' => 'Escapade bien-être à Nivelles',
                'price' => 124.00,
                'image' => 'images/store/pool.jpg',
                'description' => "Week-end détente avec spa et hammam en Belgique.",
                'category' => 'femme',
                'label' => 'loisirs',
                'stock_quantity' => 8,
            ],
            [
                'id' => 18,
                'name' => 'Plateau de bain en bambou',
                'price' => 34.00,
                'image' => 'images/store/bamboo.jpg',
                'description' => "Support pour tablette et accessoires de bain.",
                'category' => 'femme',
                'label' => 'maison',
                'stock_quantity' => 25,
            ],
            [
                'id' => 19,
                'name' => 'Sac à main Coccinelle',
                'price' => 250.00,
                'image' => 'images/store/sac.jpg',
                'description' => "Sac en cuir italien au design intemporel.",
                'category' => 'femme',
                'label' => 'accessoires',
                'stock_quantity' => 10,
            ],
            [
                'id' => 20,
                'name' => 'Luminette 3 luminothérapie',
                'price' => 229.00,
                'image' => 'images/store/luminette.jpg',
                'description' => "Lampe pour lutter contre la dépression saisonnière.",
                'category' => 'femme',
                'label' => 'technologie',
                'stock_quantity' => 5,
            ],
            [
                'id' => 21,
                'name' => 'Planétarium interactif',
                'price' => 80.00,
                'image' => 'images/store/planétarium.jpg',
                'description' => "Projette les constellations avec livret éducatif.",
                'category' => 'Enfants',
                'label' => 'loisirs',
                'stock_quantity' => 40,
            ],
            [
                'id' => 22,
                'name' => 'Kit jardinage enfant',
                'price' => 30.00,
                'image' => 'images/store/jardin.jpg',
                'description' => "Outils adaptés et graines bio, made in France.",
                'category' => 'Enfants',
                'label' => 'loisirs',
                'stock_quantity' => 60,
            ],
            [
                'id' => 23,
                'name' => 'Jeu de société Möllky',
                'price' => 50.00,
                'image' => 'images/store/molkky.jpg',
                'description' => "Jeu de quilles en bois pour apprendre en s’amusant.",
                'category' => 'Enfants',
                'label' => 'loisirs',
                'stock_quantity' => 30,
            ],
            [
                'id' => 24,
                'name' => 'Doudou lapin personnalisable',
                'price' => 37.00,
                'image' => 'images/store/lapin.jpg',
                'description' => "Doudou lavable brodé au prénom de l’enfant.",
                'category' => 'Enfants',
                'label' => 'accessoires',
                'stock_quantity' => 50,
            ],
            [
                'id' => 25,
                'name' => 'Puzzle Pompier 24 pièces',
                'price' => 27.00,
                'image' => 'images/store/puzzle.jpg',
                'description' => "Puzzle éducatif avec grandes pièces solides.",
                'category' => 'Enfants',
                'label' => 'loisirs',
                'stock_quantity' => 40,
            ],
            [
                'id' => 26,
                'name' => 'Tapis de jeu Royaume des animaux',
                'price' => 66.00,
                'image' => 'images/store/tapis.jpg',
                'description' => "Tapis coloré pour l’éveil sensoriel.",
                'category' => 'Enfants',
                'label' => 'maison',
                'stock_quantity' => 20,
            ],
            [
                'id' => 27,
                'name' => 'Veilleuse tortue en bois',
                'price' => 79.00,
                'image' => 'images/store/torte.jpg',
                'description' => "Veilleuse apaisante en matériaux durables.",
                'category' => 'Enfants',
                'label' => 'accessoires',
                'stock_quantity' => 15,
            ],
            [
                'id' => 28,
                'name' => 'Sac à dos Forêt enchantée',
                'price' => 27.00,
                'image' => 'images/store/sac-a-dos.jpg',
                'description' => "Petit sac à dos avec motifs féériques.",
                'category' => 'Enfants',
                'label' => 'accessoires',
                'stock_quantity' => 35,
            ],
            [
                'id' => 29,
                'name' => 'Pâte à modeler réutilisable',
                'price' => 20.00,
                'image' => 'images/store/pate.jpg',
                'description' => "Non toxique, textures variées et amusantes.",
                'category' => 'Enfants',
                'label' => 'loisirs',
                'stock_quantity' => 100,
            ],
            [
                'id' => 30,
                'name' => 'Livre d’éveil musical',
                'price' => 54.00,
                'image' => 'images/store/musical.jpg',
                'description' => "Livre interactif avec comptines et sons.",
                'category' => 'Enfants',
                'label' => 'loisirs',
                'stock_quantity' => 80,
            ],
            [
                'id' => 31,
                'name' => 'Portrait personnalisé animal',
                'price' => 40.00,
                'image' => 'images/store/potrait.jpg',
                'description' => "Portrait ou puzzle basé sur une photo de l’animal.",
                'category' => 'Animaux',
                'label' => 'accessoires',
                'stock_quantity' => 25,

            ],
            [
                'id' => 32,
                'name' => 'Collier GPS connecté',
                'price' => 180.00,
                'image' => 'images/store/collier.jpg',
                'description' => "Collier avec géolocalisation en temps réel.",
                'category' => 'Animaux',
                'label' => 'technologie',
                'stock_quantity' => 15,
            ],
            [
                'id' => 33,
                'name' => 'Panier chauffant pour chat',
                'price' => 60.00,
                'image' => 'images/store/chat.jpg',
                'description' => "Panier lavable en mousse à mémoire de forme.",
                'category' => 'Animaux',
                'label' => 'maison',
                'stock_quantity' => 20,
            ],
            [
                'id' => 34,
                'name' => 'Jouet distributeur de friandises',
                'price' => 30.00,
                'image' => 'images/store/jouet.jpg',
                'description' => "Stimule l’intelligence avec friandises.",
                'category' => 'Animaux',
                'label' => 'loisirs',
                'stock_quantity' => 50,
            ],
            [
                'id' => 35,
                'name' => 'Kit soin pour chien à poils longs',
                'price' => 30.00,
                'image' => 'images/store/kit-chien.jpg',
                'description' => "Brosse et shampoing bio pour chiens.",
                'category' => 'Animaux',
                'label' => 'soins',
                'stock_quantity' => 70,
            ],
            [
                'id' => 36,
                'name' => 'Harnais ergonomique pour chien',
                'price' => 50.00,
                'image' => 'images/store/hanaris.jpg',
                'description' => "Confortable et réfléchissant pour les randonnées.",
                'category' => 'Animaux',
                'label' => 'accessoires',
                'stock_quantity' => 45,
            ],
            [
                'id' => 37,
                'name' => 'Fontaine à eau filtrante',
                'price' => 65.00,
                'image' => 'images/store/fontaine.jpg',
                'description' => "Encourage l’hydratation avec bruit doux.",
                'category' => 'Accessoires',
                'label' => 'maison',
                'stock_quantity' => 30,
            ],
            [
                'id' => 38,
                'name' => 'Niche en bois design',
                'price' => 200.00,
                'image' => 'images/store/niche.jpg',
                'description' => "Niche isolante et personnalisable.",
                'category' => 'Animaux',
                'label' => 'maison',
                'stock_quantity' => 10,
            ],
            [
                'id' => 39,
                'name' => 'Suspension murale pour chat',
                'price' => 120.00,
                'image' => 'images/store/chat3.jpg',
                'description' => "Espace modulable pour grimper.",
                'category' => 'Animaux',
                'label' => 'accessoires',
                'stock_quantity' => 25,
            ],
            [
                'id' => 40,
                'name' => 'Coffret jouets durables',
                'price' => 35.00,
                'image' => 'images/store/Coffretjouetsdurables.jpg',
                'description' => "Coffret de jouets en matériaux recyclés.",
                'category' => 'Animaux',
                'label' => 'loisirs',
                'stock_quantity' => 60,
            ],
            [
                'id' => 41,
                'name' => 'Carte cadeau multi-enseignes',
                'price' => 75.00,
                'image' => 'images/store/carte_cadeaux.jpg',
                'description' => "Valable chez plus de 200 marques.",
                'category' => 'Accessoires',
                'label' => 'accessoires',
                'stock_quantity' => 30,
            ],
            [
                'id' => 42,
                'name' => 'Gourde personnalisable Stanley',
                'price' => 50.00,
                'image' => 'images/store/stanley.jpg',
                'description' => "Gourde isotherme avec base pour voiture.",
                'category' => 'femme',
                'label' => 'accessoires',
                'stock_quantity' => 20,
            ],
            [
                'id' => 43,
                'name' => 'Bougie parfumée Corse',
                'price' => 38.00,
                'image' => 'images/store/candle.jpg',
                'description' => "Bougie à la cire végétale senteur Méditerranée.",
                'category' => 'femme',
                'label' => 'maison',
                'stock_quantity' => 15,
            ],
            [
                'id' => 44,
                'name' => 'Chaussettes fantaisie recyclées',
                'price' => 11.00,
                'image' => 'images/store/chaussettes.jpg',
                'description' => "Coton recyclé avec motifs originaux.",
                'category' => 'Accessoires',
                'label' => 'accessoires',
                'stock_quantity' => 100,
            ],
            [
                'id' => 45,
                'name' => 'Plateau apéro Ping Pong',
                'price' => 58.00,
                'image' => 'images/store/pigpong.jpg',
                'description' => "Plateau en bois avec jeu intégré.",
                'category' => 'Accessoires',
                'label' => 'maison',
                'stock_quantity' => 50,
            ],
            [
                'id' => 46,
                'name' => 'Tote bag océan recyclé',
                'price' => 20.00,
                'image' => 'images/store/tote.png',
                'description' => "1€ reversé à la protection marine.",
                'category' => 'Accessoires',
                'label' => 'accessoires',
                'stock_quantity' => 30,
            ],
            [
                'id' => 47,
                'name' => 'Horloge en chêne massif',
                'price' => 84.00,
                'image' => 'images/store/horlage.jpg',
                'description' => "Horloge locale au design épuré.",
                'category' => 'Accessoires',
                'label' => 'maison',
                'stock_quantity' => 20,
            ],
            [
                'id' => 48,
                'name' => 'Gobelets à whisky gravés',
                'price' => 35.00,
                'image' => 'images/store/whiskey.jpeg',
                'description' => "Cristal taillé avec gravure personnalisée.",
                'category' => 'homme',
                'label' => 'accessoires',
                'stock_quantity' => 15,
            ],
            [
                'id' => 49,
                'name' => 'Brume parfumée pour oreiller',
                'price' => 20.00,
                'image' => 'images/store/perfume.jpg',
                'description' => "Parfum lavande et bois sacré.",
                'category' => 'femme',
                'label' => 'soins',
                'stock_quantity' => 10,
            ],
            [
                'id' => 50,
                'name' => 'Pochette ordinateur ardoise',
                'price' => 50.00,
                'image' => 'images/store/pochette-ordinateur-personnalisable-764313366.png',
                'description' => "Pochette personnalisée anti-choc.",
                'category' => 'Accessoires',
                'label' => 'accessoires',
                'stock_quantity' => 5,
            ]
        ];

        foreach ($products as $productData) {
            $gift = new Gift();
            $gift->setName($productData['name']);
            $gift->setPrice($productData['price']);
            $gift->setImage($productData['image']);    
            $gift->setDescription($productData['description']);
            $gift->setCategory($productData['category']);
            $gift->setLabel($productData['label']);
            $gift->setStockQuantity($productData['stock_quantity']);
            
            $manager->persist($gift);
        }

        $manager->flush();
    }
}
